@startuml gestor_streaming
title Netflix (Gestión de contenidos)

interface IReproducible {
  + reproducir(): void
  + mostrarInfo(): void
}

interface ITemporal {
  + calcularDuracionTotal(): int
}

abstract class Contenido {
  # id: string
  # titulo: string
  # genero: string
  ---
  + Contenido(id: string, titulo: string, genero: string)
  + getId(): string
  + getTitulo(): string
  + getGenero(): string
  + {abstract} mostrarInfo(): void
}

class GestorContenidos {
  - contenidos: <Contenido>
  ---
  + agregarContenido(c: Contenido): void
  + operator+(c: Contenido): void
  + eliminarContenido(id: string): void
  + listarContenidos(): void
  + listarContenidosPorGenero(g: string): void
  + buscarPorId(id: string): void
  + buscarPorTitulo(t: string): void
}

class Pelicula {
  - anio: int
  - duracion: int
  ---
  + mostrarInfo(): void
  + reproducir(): void
  + calcularDuracionTotal(): int
}

class Serie {
  - temporadas: <Temporada>
  - anio: int
  ---
  + reproducir(): void
  + mostrarInfo(): void
  + calcularDuracionTotal(): int
}

class Juego {
  - offline: boolean
  - multijugador: boolean
  - dificultad: Dificultad
  ---
  + mostrarInfo(): void
  + reproducir(): void
}

enum Dificultad {
  FACIL
  MEDIA
  DIFICIL
}

class Temporada {
  - numTemporada: int
  - episodios: <Episodio>
  ---
  + reproducir(): void
  + mostrarInfo(): void
  + calcularDuracionTotal(): int
}

class Episodio {
  - titulo: string
  - duracion: int
  ---
  + reproducir(): void
  + calcularDuracionTotal(): int
  + mostrarInfo(): void
}

' Jerarquía principal
Contenido <|-- Pelicula
Contenido <|-- Serie
Contenido <|-- Juego

' Interfaces
Contenido ..|> IReproducible
Episodio ..|> IReproducible
Temporada ..|> IReproducible

Pelicula ..|> ITemporal
Serie ..|> ITemporal
Temporada ..|> ITemporal
Episodio ..|> ITemporal

' Composiciones
GestorContenidos "1" *-- "*" Contenido
Serie "1" *-- "*" Temporada
Temporada "1" *-- "*" Episodio

' Dependencia
Juego ..> Dificultad

@enduml